name: platform_check
description: A plugin for checking the current flutter platform, with support for web
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.buntagon.platform_check
        pluginClass: PlatformCheckPlugin
      ios:
        pluginClass: PlatformCheckPlugin
      web:
        pluginClass: PlatformCheckPlugin
        fileName: platform_check_web.dart

